version: "3.8"
services:
  user:
    build: .
    restart: always
    ports:
      - 8084:8084
    depends_on:
      - mongodb-user
    environment:
      eureka.client.service-url.defaultZone: http://airline:8761/eureka
  mongodb-user:
    image: mongo
    container_name: mongodb-user
    ports:
      - 29017:27017
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  mongo-express-user:
    image: mongo-express
    container_name: mongo-express_user
    restart: always
    ports:
      - 8091:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb-user
volumes:
  data: {}

networks:
  default:
    name: service-discovery_default